---
title: "PS0014-Figur-S3"
output: github_document
Author: "Prachi Sao"
Date: "2021-06-30"
organization:"PAUKEN LAB, MD ANDERSON CANCER CENTER"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load colors
```{r}  
<!-- # set colors for plots  -->
my_colors_cluster <- c('red','black','blue','green','orange','yellow','brown','magenta','pink','gray')
my_colors_sample <- c('purple', 'tan','lightblue','lightgreen','maroon','lightgreen','lightpink','yellow',"orange","lightblue")
my_colors_cp_status =c("blue", "gray90")
```

## Load Data
```{r}
no_tcr_final = readRDS("Results /RDS/PS00111-cd8_cca_integrated_res04_final_04_22_2024_final.rds")
names(no_tcr_final@meta.data)
```

```{r}

co_expression = c("PDCD1", "HAVCR2", "TIGIT", "LAG3", "CTLA4", "CD160")
no_tcr_final[["RNA"]]$data[co_expression,]

# new_metadata <- data.frame(coexpression = rowSums(as.data.frame(t(as.data.frame(no_tcr_final[["RNA"]]$data[co_expression,]))) > 0))
# no_tcr_final<- AddMetaData(no_tcr_final, new_metadata)
```

## Figure S3 A
```{r}
dittoDimPlot(no_tcr_final, "coexpression", split.by = "coexpression",  color.panel = colorRampPalette(brewer.pal(7, "Blues"))(7), 
  colors = seq_along(color.panel))
```

## Figure S3 B
```{r}
Idents(no_tcr_final) = "seurat_cluster.04"

my_colors_stackedbarplot <- colorRampPalette(brewer.pal(7, "Blues"))(7) 

Idents(no_tcr_final) = "coexpression"

pt_co  = table(Idents(no_tcr_final), no_tcr_final$seurat_cluster.04)
pt_co <- as.data.frame(pt_co)
pt_co$Var1 <- as.character(pt_co$Var1)

Figure.S3.B = ggplot(pt_co, aes(x = Var2, y = Freq, fill = Var1)) +
  theme_bw(base_size = 15) +
  geom_col(position = "fill", width = 0.5) +
  xlab("Cluster Number") +
  labs(fill='IRs') +
  ylab("Percentage of cells co-expressing the indicated number of IRs") +
  scale_fill_manual(values = my_colors_stackedbarplot) +
  theme(legend.title = element_blank()) +theme_classic()
  Figure.S3.B
```

## Figure S3 C
```{r}
Idents(no_tcr_final)  = "seurat_cluster.04"

FigS1D_gene_list = c("PDCD1", "HAVCR2", "LAG3", "BTLA", "CD160", "CTLA4", "TIGIT", "ENTPD1", "CD244", "PROCR", "PDPN", "CD200",
"TNFRSF9", "TNFRSF18", "CD27", "CD28", "CD226", "CD40LG",
"TCF7", "CCR7", "SELL", "IL7R", "LEF1", "KLF2",
"GZMB", "PRF1", "GZMA", "GZMK", "IFNG", "TNF", "IL2",
"ITGAE", "ITGA1", "CDH1", "CXCR6",
"NR4A1", "EOMES", "HIF1A", "TOX", "ZEB2", "ID2", "ID3", "BHLHE40","CXCL13",
"CXCR3", "CX3CR1", "KLRG1", "CD101", "ENO1", "GAPDH", "ALDOA", "PGK1", "LDHA")

#TXB21 is not available in data

aggregate_FigS1D_gene_list_df<- as.data.frame(AggregateExpression(no_tcr_final, features = FigS1D_gene_list, group.by ="seurat_cluster.04", return.seurat = F, assays = "RNA"))


#organize the dataframe rows acording to gene_list
aggregate_FigS1D_gene_list_df<- data.matrix(aggregate_FigS1D_gene_list_df)[match(FigS1D_gene_list, rownames(data.matrix(aggregate_FigS1D_gene_list_df))),]

colnames(aggregate_FigS1D_gene_list_df) = c(levels(no_tcr_final))

#write.table(aggregate_FigS1D_gene_list_df, file = paste0(dir_out, "final_plots/", "mor_FigS3D_mat05-06-2024.txt"))

#order the rows by the  FigS1D_gene_list


scaled.mat2 <- t(scale(t(aggregate_FigS1D_gene_list_df)))
FigS1D.mat = data.matrix(scaled.mat2)[match(FigS1D_gene_list, rownames(data.matrix(scaled.mat2))),]
data.matrix(FigS1D.mat)

library(pheatmap)

input.hm.filter.breaks <- t(scale(t(FigS1D.mat )))
quantile.range <- quantile(t(input.hm.filter.breaks), probs = seq(0, 1, 0.1))
paletteBreaks <- quantile.range
paletteLength <- length(paletteBreaks)-1
col.pal <- RColorBrewer::brewer.pal(paletteLength, "RdBu")
col.pal <- rev(col.pal)

pheatmap(
    mat               = FigS1D.mat,
    breaks            = paletteBreaks,
    cluster_cols      = FALSE,
    cluster_rows      = FALSE,
    color             = col.pal,
    border_color      = NA,
    show_colnames     = T,
    show_rownames     = T,
    drop_levels       = TRUE,
    fontsize          = 14,
    main              = "figS1D",
      # Add this line to reorder the heatmap based on column
)
```